// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VRchatGroupDataCollector.Models;

[Table("events")]
public partial class Event
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("worlddata")]
    public int Worlddata { get; set; }

    [Column("instanceID")]
    public int InstanceId { get; set; }

    [Required]
    [Column("regon")]
    public string Regon { get; set; }

    [Column("firstlogtime")]
    public DateTime? Firstlogtime { get; set; }

    [Column("lastlogtime")]
    public DateTime? Lastlogtime { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<PlayerActivity> PlayerActivities { get; set; } = new List<PlayerActivity>();

    [ForeignKey("Worlddata")]
    [InverseProperty("Events")]
    public virtual WorldDatum WorlddataNavigation { get; set; }
}