// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VRchatGroupDataCollector.Models;

[Table("PlayerActivity")]
public partial class PlayerActivity
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("eventID")]
    public int EventId { get; set; }

    [Column("PlayerID")]
    public int PlayerId { get; set; }

    [Column("time")]
    public DateTime Time { get; set; }

    public bool Joined { get; set; }

    public int TotalPlayerCount { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("PlayerActivities")]
    public virtual Event Event { get; set; }

    [ForeignKey("PlayerId")]
    [InverseProperty("PlayerActivities")]
    public virtual Player Player { get; set; }
}