// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace VRchatGroupDataCollector.Models;

[Table("worldData")]
public partial class WorldDatum
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("vrchatWorldID")]
    public string VrchatWorldId { get; set; }

    [InverseProperty("WorlddataNavigation")]
    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}